"""
BCW Barcode Agent
=================
Generates scannable labels (QR + Code128) for firearms and resolves a scanned
code back to the full MAGAZZINO record.

Lookup key = weapon serial (MATR. ARMA, col I). Codes generated by BCW encode
the serial as  BCW|<serial>  (also stored plain). Manufacturer barcodes that
arrive on incoming guns are stored in col Y (CODICE A BARRE) at intake so a
later scan of that same code maps straight back to the row.

Usage:
    python barcode_agent.py genera '<json>'   # make label(s) + write code to col Y
    python barcode_agent.py scan   '<json>'   # resolve a scanned string -> full record
    python barcode_agent.py link   '<json>'   # attach a maker barcode to an existing row

GENERA JSON:
    matr_arma      str            single item by serial            (optional)
    n_operazione   int            single item by operation number  (optional)
    items          list           batch: [{"matr_arma": "..."}, {"n_operazione": 1}]
    label_mm       [w, h]         label size in mm (default [57, 32])
    out            str            output PDF name (default barcode_labels.pdf)
    If neither matr_arma/n_operazione/items given -> all in-stock weapons with a serial.

SCAN JSON:
    code           str            the raw scanned string (required)

LINK JSON:  (record a maker's barcode that came on an incoming gun)
    matr_arma      str  OR  n_operazione int   -> which row
    code           str            the scanned maker barcode value (required)
"""

import json
import sys
import os
import io
import shutil
from datetime import datetime

import openpyxl
from openpyxl import load_workbook

import qrcode
import barcode as barcode_lib
from barcode.writer import ImageWriter

from reportlab.lib.units import mm
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas as pdfcanvas

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
EXCEL_FILE = os.path.join(SCRIPT_DIR, "MAGAZZINO BCW V45.xlsx")
LABELS_DIR = os.path.join(SCRIPT_DIR, "labels")

CODE_COL = 25  # col Y  CODICE A BARRE
SERIAL_COL = 9  # col I  MATR. ARMA
NOP_COL = 2  # col B  N. OPERAZIONE
BCW_PREFIX = "BCW|"

HEADERS = [
    "GIACENZA", "N_OPERAZIONE", "DATA_CARICO", "QUANTITA", "TIPOLOGIA",
    "CALIBRO", "MARCA", "MODELLO", "MATR_ARMA", "MATR_CANNA", "MATR_AGG",
    "FORNITORE", "COSTO", "COSTO_IMBALLO", "COSTO_COMPL",
    "DATA_DDT", "DATA_FATTURA_ACQ",
    "PREZZO_VENDITA", "V", "N_ATA", "DATA_SCARICO",
    "N_FATTURA_VEND", "DATA_FATTURA_VEND", "CLIENTE", "CODICE_A_BARRE",
]


# ── workbook helpers ─────────────────────────────────────────────────────────

def load_wb():
    return load_workbook(EXCEL_FILE, data_only=False)


def save_wb(wb):
    backup = EXCEL_FILE.replace(".xlsx", "_backup.xlsx")
    if os.path.exists(EXCEL_FILE):
        shutil.copy2(EXCEL_FILE, backup)
    wb.save(EXCEL_FILE)


def _fmt(v):
    if isinstance(v, datetime):
        return v.strftime("%d/%m/%Y")
    return v


def row_to_dict(ws, row):
    d = {}
    for col, header in enumerate(HEADERS, start=1):
        d[header] = _fmt(ws.cell(row, col).value)
    d["row"] = row
    return d


def find_row_by_key(ws, matr_arma=None, n_operazione=None):
    """Find a MAGAZZINO row by serial (col I) or operation number (col B)."""
    matr = str(matr_arma).strip() if matr_arma else ""
    for r in range(2, ws.max_row + 1):
        if matr and matr not in ("", "N/D"):
            v = ws.cell(r, SERIAL_COL).value
            if v is not None and str(v).strip() == matr:
                return r
        if n_operazione:
            v = ws.cell(r, NOP_COL).value
            if v is not None:
                try:
                    if int(v) == int(n_operazione):
                        return r
                except (ValueError, TypeError):
                    pass
    return None


def resolve_scan(ws, code):
    """Resolve a raw scanned string to a row.

    Order: strip BCW| prefix -> match serial (col I) -> match maker code (col Y)
    -> match operation number (col B).
    """
    raw = str(code).strip()
    candidate = raw[len(BCW_PREFIX):].strip() if raw.startswith(BCW_PREFIX) else raw

    # 1) serial match
    for r in range(2, ws.max_row + 1):
        v = ws.cell(r, SERIAL_COL).value
        if v is not None and str(v).strip() == candidate:
            return r, "matr_arma"
    # 2) stored maker code match (col Y) — match raw or candidate
    for r in range(2, ws.max_row + 1):
        v = ws.cell(r, CODE_COL).value
        if v is not None and str(v).strip() in (raw, candidate):
            return r, "codice_a_barre"
    # 3) operation number match
    if candidate.isdigit():
        for r in range(2, ws.max_row + 1):
            v = ws.cell(r, NOP_COL).value
            if v is not None:
                try:
                    if int(v) == int(candidate):
                        return r, "n_operazione"
                except (ValueError, TypeError):
                    pass
    return None, None


# ── image builders ───────────────────────────────────────────────────────────

def make_qr_png(payload):
    qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_M, box_size=10, border=2)
    qr.add_data(payload)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return buf


def make_code128_png(payload):
    Code128 = barcode_lib.get_barcode_class("code128")
    writer = ImageWriter()
    bc = Code128(payload, writer=writer)
    buf = io.BytesIO()
    bc.write(buf, options={"module_height": 12.0, "font_size": 8, "text_distance": 3.0, "quiet_zone": 2.0})
    buf.seek(0)
    return buf


# ── label PDF ────────────────────────────────────────────────────────────────

def build_labels(items, label_mm, out_path):
    """items: list of dicts with keys serial, marca, modello, calibro, n_op, payload."""
    w = label_mm[0] * mm
    h = label_mm[1] * mm
    c = pdfcanvas.Canvas(out_path, pagesize=(w, h))

    for it in items:
        payload = it["payload"]
        qr_buf = make_qr_png(payload)
        bc_buf = make_code128_png(payload)

        pad = 2 * mm
        qr_size = h - 2 * pad
        # QR on the left
        c.drawImage(ImageReader(qr_buf), pad, pad, qr_size, qr_size,
                    preserveAspectRatio=True, mask="auto")

        text_x = pad + qr_size + 2 * mm
        text_w = w - text_x - pad

        def fit(txt, font, size):
            """Truncate txt so it fits within text_w at the given font/size."""
            txt = str(txt)
            from reportlab.pdfbase.pdfmetrics import stringWidth
            if stringWidth(txt, font, size) <= text_w:
                return txt
            while txt and stringWidth(txt + "…", font, size) > text_w:
                txt = txt[:-1]
            return txt + "…"

        # text block on the right
        line_y = h - pad - 7
        if it.get("marca"):
            c.setFont("Helvetica-Bold", 8)
            c.drawString(text_x, line_y, fit(it["marca"], "Helvetica-Bold", 8))
            line_y -= 9
        if it.get("modello"):
            c.setFont("Helvetica-Bold", 7)
            c.drawString(text_x, line_y, fit(it["modello"], "Helvetica-Bold", 7))
            line_y -= 9
        c.setFont("Helvetica", 7)
        if it.get("calibro"):
            c.drawString(text_x, line_y, fit(f"Cal. {it['calibro']}", "Helvetica", 7))
            line_y -= 9
        c.drawString(text_x, line_y, fit(f"SN: {it.get('serial', '')}", "Helvetica", 7))
        line_y -= 9
        if it.get("n_op"):
            c.drawString(text_x, line_y, fit(f"N.OP {it['n_op']}", "Helvetica", 7))

        # Code128 across the bottom of the text column
        bc_h = 9 * mm
        bc_w = text_w
        c.drawImage(ImageReader(bc_buf), text_x, pad, bc_w, bc_h,
                    preserveAspectRatio=True, anchor="sw", mask="auto")

        c.showPage()

    c.save()


# ── commands ─────────────────────────────────────────────────────────────────

def _collect_items(ws, data):
    """Return list of (row, serial, marca, modello, calibro, n_op)."""
    rows = []
    if data.get("items"):
        for spec in data["items"]:
            r = find_row_by_key(ws, spec.get("matr_arma"), spec.get("n_operazione"))
            if r:
                rows.append(r)
    elif data.get("matr_arma") or data.get("n_operazione"):
        r = find_row_by_key(ws, data.get("matr_arma"), data.get("n_operazione"))
        if r:
            rows.append(r)
    else:
        # all in-stock weapons with a serial
        for r in range(2, ws.max_row + 1):
            tip = ws.cell(r, 5).value
            serial = ws.cell(r, SERIAL_COL).value
            v = ws.cell(r, 19).value  # V (sold)
            if tip in (None, "") or serial in (None, "", "N/D"):
                continue
            if v and int(v) > 0:
                continue
            rows.append(r)
    return rows


def cmd_genera(data):
    wb = load_wb()
    ws = wb["MAGAZZINO"]

    rows = _collect_items(ws, data)
    if not rows:
        return {"status": "error", "message": "Nessun articolo trovato per generare etichette."}

    label_mm = data.get("label_mm", [57, 32])
    out_name = data.get("out", "barcode_labels.pdf")
    os.makedirs(LABELS_DIR, exist_ok=True)
    out_path = os.path.join(LABELS_DIR, out_name)

    items = []
    written = 0
    for r in rows:
        serial = ws.cell(r, SERIAL_COL).value
        n_op = ws.cell(r, NOP_COL).value
        if serial in (None, "", "N/D"):
            # no serial -> encode operation number so it stays scannable
            if n_op in (None, ""):
                continue
            payload = str(int(n_op))
        else:
            payload = f"{BCW_PREFIX}{str(serial).strip()}"

        # store the code we generated in col Y if that cell is empty
        if ws.cell(r, CODE_COL).value in (None, ""):
            ws.cell(r, CODE_COL).value = payload
            written += 1

        items.append({
            "payload": payload,
            "serial": str(serial).strip() if serial not in (None, "") else "",
            "marca": ws.cell(r, 7).value,
            "modello": ws.cell(r, 8).value,
            "calibro": ws.cell(r, 6).value,
            "n_op": int(n_op) if n_op not in (None, "") else None,
        })

    if not items:
        return {"status": "error", "message": "Articoli trovati ma senza serial né N.OPERAZIONE codificabili."}

    build_labels(items, label_mm, out_path)
    save_wb(wb)

    return {
        "status": "success",
        "message": f"{len(items)} etichetta/e generate.",
        "pdf": out_path,
        "labels": len(items),
        "codici_scritti_in_Y": written,
        "label_mm": label_mm,
    }


def cmd_scan(data):
    code = data.get("code")
    if not code:
        return {"status": "error", "message": "Campo 'code' mancante."}
    wb = load_wb()
    ws = wb["MAGAZZINO"]
    row, matched_by = resolve_scan(ws, code)
    if row is None:
        return {"status": "not_found", "message": f"Nessun articolo per il codice: {code}"}
    result = row_to_dict(ws, row)
    result["status"] = "found"
    result["matched_by"] = matched_by
    result["venduto"] = bool(ws.cell(row, 19).value and int(ws.cell(row, 19).value) > 0)
    return result


def cmd_link(data):
    code = data.get("code")
    if not code:
        return {"status": "error", "message": "Campo 'code' mancante."}
    wb = load_wb()
    ws = wb["MAGAZZINO"]
    row = find_row_by_key(ws, data.get("matr_arma"), data.get("n_operazione"))
    if row is None:
        return {"status": "error", "message": "Articolo non trovato (matr_arma / n_operazione)."}
    existing = ws.cell(row, CODE_COL).value
    ws.cell(row, CODE_COL).value = str(code).strip()
    save_wb(wb)
    return {
        "status": "success",
        "message": f"Codice fornitore '{code}' collegato alla riga {row}.",
        "row": row,
        "sovrascritto": existing if existing not in (None, "") else None,
    }


# ── main ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(json.dumps({"status": "error", "message": "Specifica: genera | scan | link"}))
        sys.exit(1)

    cmd = sys.argv[1].lower()
    data = {}
    if len(sys.argv) >= 3:
        try:
            data = json.loads(sys.argv[2])
        except json.JSONDecodeError as e:
            print(json.dumps({"status": "error", "message": f"JSON non valido: {e}"}))
            sys.exit(1)

    if cmd == "genera":
        result = cmd_genera(data)
    elif cmd == "scan":
        result = cmd_scan(data)
    elif cmd == "link":
        result = cmd_link(data)
    else:
        result = {"status": "error", "message": f"Comando sconosciuto: {cmd}"}

    print(json.dumps(result, ensure_ascii=False, indent=2, default=str))
